# Generated by Django 2.2.14 on 2021-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20210806_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='justificativa',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
