# Generated by Django 2.2.14 on 2021-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_certificado_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
